export const STATIC_STRINGS = {
  CONTENT: {},
  BUTTON: {},
  NAV_OPTIONS: {
    HOME: "Home",
    MEN: "Men",
    WOMEN: "Women",
  },
  FOOTER: {
    LINK_HEADINGS: {
      ONLINE_SHOPPING: "ONLINE SHOPPING",
      CUSTOMER_POLICES: "CUSTOMER POLICIES",
      USEFUL_LINKS: "USEFULL LINKS",
      EXPERINCE: "EXPERIENCE MYNTRA APP ON MOBILE",
      KEEP_IN_TOUCH: "KEEP IN TOUCH",
    },
    FOOTER_NAVLINKS_VAR1: {
      MEN: "Men",
      WOMEN: "Women",
      KIDS: "Kids",
      HOME_AND_LIVING: "Home & Living",
      BEAUTY: "Beauty",
      GIFT_CARDS: "Gift Cards",
      MYNTRA_INSIDER: "Myntra Insider",
    },
    FOOTER_NAVLINKS_VAR2: {
      BLOG: "Blog",
      CAREERS: "Careers",
      SITE_MAP: "Site Map",
      CORPORATE_INFORMATION: "Corporate Information",
      WHITEHAT: "Whitehat",
      CLEARTRIP: "Cleartrip",
    },
    FOOTER_NAVLINKS_VAR3: {
      CONTACT_US: "Contact Us",
      FAQ: "FAQ",
      T_C: "T&C",
      TERMS_OF_USE: "Terms Of Use",
      TRACK_ORDERS: "Track Orders",
      SHIPPING: "Shipping",
      CANCELLATION: "Cancellation",
      RETURNS: "Returns",
      PRIVACY_POLICY: "Privacy Policy",
      GRIEVANCE_OFFICER: "Grievance Officer",
    },
  },
};
